name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm init -y
        npm install express mysql2 cors dotenv

    - name: Run unit tests
      run: |
        cd kasir-backend
        npm start &

    - name: wait for sleep
      run: sleep 5

    - name: Stop server
      run: lsof -t -i:3000 | xargs -r kill

    
